apiVersion: v1
kind: Pod
metadata:
  name: nfs
spec:
  containers:
    - name: nfs
      image: ubuntu
      volumeMounts:
        - name: nfs
          mountPath: "/data-mount"
  volumes:
  - name: nfs
    nfs:
      server: 192.168.20.145
      path: "/"
