apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "pvnfs01"
spec:
  capacity:
    storage: "3Gi"
  accessModes:
    - "ReadWriteOnce"
  nfs:
    path: "/"
    server: "192.168.20.145"
  persistentVolumeReclaimPolicy: "Recycle"
