apiVersion: v1
kind: Pod
metadata:
  name: guaranteed-pod2
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: 0.3
        memory: 300Mi
      requests:
        cpu: 0.3
        memory: 250Mi
