apiVersion: v1
kind: Pod
metadata:
  name: secret-example2-volume
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["/bin/sh", "-c", "while : ;do cat /secret/token; sleep 10; done"]
    volumeMounts:
    - name: secret-volume
      mountPath: /secret
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: access-token
      items:
      - key: access-test-token
        path: token
